enum Type {
    REGISTER,
    REGISTERED,
    REGISTER_DENIED,
    DEREGISTER,
    DEREGISTERED,
    NOT_REGISTERED,
    PUBLISH,
    PUBLISHED,
    PUBLISH_DENIED,
    REMOVE,
    REMOVED,
    REMOVE_DENIED,
    UPDATE,
    UPDATE_SERVER,
    UPDATE_CONTACT,
    UPDATE_CONFIRMED,
    UPDATE_DENIED,
    FILE_REQ,
    FILE_CONF,
    FILE,
    FILE_END,
    FILE_ERROR
}

enum Reason {
    CLIENT_NAME_ALREADY_IN_USE,
    CLIENT_NAME_DNE,
    IP_ADDRESS_AND_PORT_NOT_CHANGED,
    UNKNOWN_CLIENT,
    FILE_NOT_FOUND,
    DUPLICATE_FILE
}
